# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Getopt-Std-WithCheck
version:      0.04
version_from: lib/Getopt/Std/WithCheck.pm
installdirs:  site
requires:
    Getopt::Std:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
